# фото старт
start_inc = 'AgACAgIAAxkDAAICVWAy8gVs7OSsVtWUH9w8uvGyYYTxAAKmsTEb2VGYSSUEQQABvcAmkTwgc5cuAAMBAAMCAAN5AAPJJAcAAR4E'

# фото которого нет
photo_kotorogo_net = "AgACAgIAAxkDAAI0LmJwUs5sRO9_f2mFeYruybu58hs2AAJXvDEbAxeAS0vHl3nXP-9dAQADAgADeAADJAQ"

# фото городов
zlin_ph = "AgACAgIAAxkDAAICUmAy8VdbbxVd3pND8eOiDgLl10AmAAKjsTEb2VGYSaeztC_xJLUt9mU6ny4AAwEAAwIAA3cAA2gzAAIeBA"
pisek_ph = 'AgACAgIAAxkDAAICO2Ay8Szw9oIvF6WOSETgDcxe3mdCAAKMsTEb2VGYSVBodAABAfLWF4rm_p4uAAMBAAMCAAN3AAOLNQACHgQ'
chomutov_ph = 'AgACAgIAAxkDAAICPGAy8S7zMPcLS8-CNZxi6UI-0aQhAAKNsTEb2VGYSUVjykvevM3y_dwSmy4AAwEAAwIAA3cAA55qAgABHgQ'
czBudevice_ph = 'AgACAgIAAxkDAAICPWAy8TKbwp0DWpjY2qPgPvyZi4FlAAKOsTEb2VGYSavvzmiFoOBlT_samC4AAwEAAwIAA3cAA_IhBwABHgQ'
kladno_ph = 'AgACAgIAAxkDAAICPmAy8TVgY1NOBD9UsukV4EnF1uGWAAKPsTEb2VGYSZ_SaeB514Iv-LEHni4AAwEAAwIAA3cAA11wAgABHgQ'
praha_ph = 'AgACAgIAAxkDAAICP2Ay8TbO0euQzAcYgJ-lYUcU9gtDAAKQsTEb2VGYSXnVeiuW2xwdlPEBny4AAwEAAwIAA3cAA801AAIeBA'
trutnov_ph = 'AgACAgIAAxkDAAICQGAy8TjX1QTFeuZlh2Mlea2RHbbMAAKRsTEb2VGYSTBrUU59l6llGCwlmy4AAwEAAwIAA3cAA-ByAwABHgQ'
plzen_ph = 'AgACAgIAAxkDAAICQmAy8TmeK52GnZmGMZ6xvrxqk-7IAAKTsTEb2VGYSZhGP-ta7m6m5-gymy4AAwEAAwIAA3cAAzVgAwABHgQ'
jindrichevHradec_ph = 'AgACAgIAAxkDAAICQ2Ay8TzutdeyIqr_BcjlfFtn6oR6AAKUsTEb2VGYSXONFs4Sy4PzQCAimy4AAwEAAwIAA3cAA_Z1AwABHgQ'
prerov_ph = 'AgACAgIAAxkDAAICRGAy8T43RNYDKUmax_aYXsxTRbI-AAKVsTEb2VGYSX-t-THYOv_bfMzKmS4AAwEAAwIAA3gAAwFEBQABHgQ'
mladaBoleslav_ph = 'AgACAgIAAxkDAAICRWAy8UCrzKOiuXU5OEfh7Yz09-58AAKWsTEb2VGYSRd7lFh8LwScL84Nni4AAwEAAwIAA3cAA1d3AgABHgQ'
jihlava_ph = 'AgACAgIAAxkDAAICRmAy8UPtWypxAAHcffk6CFqefnjbIgACl7ExG9lRmElQjT2LUUOb_G7dEpsuAAMBAAMCAAN3AAN7cAIAAR4E'
ostrava_ph = 'AgACAgIAAxkDAAICR2Ay8UZ6XTzhCHeeZKYRaZa5dhH4AAKYsTEb2VGYSfKQ9UceH3zGH-oymy4AAwEAAwIAA3cAA3RmAwABHgQ'
pribram_ph = 'AgACAgIAAxkDAAICSmAy8UjQKMWqAbVNrinyLwmVxo_AAAKbsTEb2VGYSciCGmj-WeV3cLJFmC4AAwEAAwIAA3cAAzwcBwABHgQ'
brno_ph = 'AgACAgIAAxkDAAICS2Ay8UmW-_ALaOwaGNaiWN7XZIc4AAKcsTEb2VGYSeJnoWqTuCrU3EYrmy4AAwEAAwIAA3cAA6soAwABHgQ'
benesov_ph = 'AgACAgIAAxkDAAICTGAy8UtXjLEv99ajNmhR7-ok5WDeAAKdsTEb2VGYSbBy48cte1KSrdVWmS4AAwEAAwIAA3cAA7l8BQABHgQ'
frydekMistek_ph = 'AgACAgIAAxkDAAICTWAy8U2eb7jF0UVwJvVyz_kqi32uAAKesTEb2VGYSZDxhUasPQGfYUgrmy4AAwEAAwIAA3cAA0QiAwABHgQ'
karloviVary_ph = 'AgACAgIAAxkDAAICTmAy8VALt9EHDu_WUuARi-LmI3FTAAKfsTEb2VGYSdl5cgL3X8Cb6PkYmy4AAwEAAwIAA3cAA7pqAgABHgQ'
liberec_ph = 'AgACAgIAAxkDAAICT2Ay8VIr3c__8lpYlZXxoojFH7M9AAKgsTEb2VGYSbEDR1tLMhokz1s3ny4AAwEAAwIAA3cAA8UxAAIeBA'
kutnaHora_ph = 'AgACAgIAAxkDAAICUGAy8VNytPc5098W5u1sp-GAcu-GAAKhsTEb2VGYSfuF4eXHHUHoTWsAAZ8uAAMBAAMCAAN3AANsNAACHgQ'
hradecKralove_ph = 'AgACAgIAAxkDAAICUWAy8VUi1Xc9SI_htqqf1wJ2YLp5AAKisTEb2VGYSd7r2OUpfuRBK6I-ni4AAwEAAwIAA3cAAxw1AAIeBA'
pardubice_ph = 'AgACAgIAAxkDAAICU2Ay8VppEmEQPGT25KNHrAgJHxkvAAKksTEb2VGYSWhNJzuP0PmaZuA4ny4AAwEAAwIAA3cAA9UzAAIeBA'
ustiNadLabem_ph = 'AgACAgIAAxkDAAICVGAy8VsdNuzfE2qTdwmSzN06Vk84AAKlsTEb2VGYSTd8s5fNHed66sIpmy4AAwEAAwIAA3cAA1FvAwABHgQ'

womens_cz_photo = "AgACAgIAAxkDAAIEh2BzVVjKJ2GkpdY7V2W7vbOLJfe4AAIZtDEbasqZS77Vm2y32D3QBilAni4AAwEAAwIAA20AA47YAgABHgQ"
anton_vaykhel_photo = "AgACAgIAAxkDAAIFJmB0BifqN1o5aqj5tp_1w-5xwmHrAAJ0sjEbasqhS9GAsYFBLwzou5AHoi4AAwEAAwIAA3kAAyX6AAIeBA"
evakobz_photo = "AgACAgIAAxkDAAIEimBzVVkhhHwxAjfQSyWgOdOgztc5AAIctDEbasqZS_vr-vMFb880E88Nni4AAwEAAwIAA20AA8QQBQABHgQ"
vlazegur_photo = "AgACAgIAAxkDAAIEiWBzVVjT0lL-PDpBUCadmUbxbQVjAAIbtDEbasqZS4kkNOnMOVGA6aM-ni4AAwEAAwIAA3cAAz7kAgABHgQ"
koroopaev_photo = "AgACAgIAAxkDAAIHE2C5S0XEzj6Bvr86HJ1-F_Qh9fJ7AAJ5tDEblxfJSaLKle-tTmALC-A4ny4AAwEAAwIAA20AA0W7BAABHwQ"
pragueOnline_photo = "AgACAgIAAxkDAAIHpGDlzKL9JpRqOdt9FxQGwJ2wuNPhAAKesjEb1UIxS2Js2xUlyUasAQADAgADbQADIAQ"

# фото пабл Интеграционные центры ________________________________________________
ICPrague1_jpg = "AgACAgIAAxkDAAIF-mCkE3JKFULCDDyL1jSyRd6lRus6AAKNsjEb9YwgSTyrCOVX7U_MNtAPmy4AAwEAAwIAA3cAA6M3BgABHwQ"
ICPrague2_jpg = "AgACAgIAAxkDAAIF_GCkE3TLyhxneKwaWm-42QJCgW8qAAKPsjEb9YwgScbNhZ7YsYDwl4yQoS4AAwEAAwIAA3cAA_BgAgABHwQ"
ICPrague3_jpg = "AgACAgIAAxkDAAIF_2CkE3lv7pBvzMVJeLHRsYctKce-AAKSsjEb9YwgSUJjXT81vEYNkDcFpC4AAwEAAwIAA3cAAz42AQABHwQ"
ICPrague4_jpg = "AgACAgIAAxkDAAIGAAFgpBN7gk_Iu3GI9B8f9FG068rwMgACk7IxG_WMIEn47bhOr7jHqySiAAGkLgADAQADAgADdwAD2CwBAAEfBA"
ICMladaBoleslav_jpg = "AgACAgIAAxkDAAIF8mCkE2hl5P8ETu0nyP1zW8ZKmtpMAAKFsjEb9YwgSVUqNCJP32HmiscmpC4AAwEAAwIAA3cAAzkyAQABHwQ"
ICKladno_jpg = "AgACAgIAAxkDAAIF-2CkE3N5PDrja3l4MoDjcXNsOEj1AAKOsjEb9YwgSdHmML8-FwsSaqdapC4AAwEAAwIAA3cAAygtAQABHwQ"
ICPribram_jpg = "AgACAgIAAxkDAAIGB2CkE4W0Gs_2yGwirkwkpr7Z0E-8AAKasjEb9YwgSeH-giravPtXlvESpC4AAwEAAwIAA3cAA-08AQABHwQ"
ICKutnaHora_jpg = "AgACAgIAAxkDAAIGA2CkE3_7sMRRI2iBKzVKnfWL1QKeAAKWsjEb9YwgSWBzkPBNFG6jEpeAny4AAwEAAwIAA3cAA-FXBAABHwQ"
ICBenesov_jpg = "AgACAgIAAxkDAAIF_WCkE3ZuzIoOiuOvDbRwjgunaz5KAAKQsjEb9YwgSaXE6wABt9oJl-RcDqQuAAMBAAMCAAN3AAN8LQEAAR8E"
ICHradecKralove_jpg = "AgACAgIAAxkDAAIF-GCkE2_75iDBDa2Rdy4j1xe4GVJvAAKLsjEb9YwgSY0ffggQHnK44iUfpC4AAwEAAwIAA3cAA-E1AQABHwQ"
ICBrno_jpg = "AgACAgIAAxkDAAIF92CkE25clKl707YNeUD41bYj3FW0AAKKsjEb9YwgSQ8eMa6p23ETUDOjoi4AAwEAAwIAA3cAA1Z6AgABHwQ"
ICUstiNadLabem_jpg = "AgACAgIAAxkDAAIGBmCkE4QX3G6rv-jiKcTXSyvW0YX4AAKZsjEb9YwgSRmRKd3iD-swTZ8dpC4AAwEAAwIAA3cAA283AQABHwQ"
ICTeplice_jpg = "AgACAgIAAxkDAAIF9WCkE22GRzrFUkiG_Sb-EhGiWvhNAAKIsjEb9YwgSa3y65krHOn2k9I1ny4AAwEAAwIAA3cAA2NmBAABHwQ"
ICZlin_jpg = "AgACAgIAAxkDAAIGBWCkE4Jcr3nVYd9i6mCP1o13pGiMAAKYsjEb9YwgSSo5hWvh5DR60lmlmy4AAwEAAwIAA3cAA0EFAQABHwQ"
ICOstrava_jpg = "AgACAgIAAxkDAAIF_mCkE3edNJvupX_y7dVp5ovKSQtiAAKRsjEb9YwgSbLNjxnbU0XV3SQfpC4AAwEAAwIAA3cAA6g0AQABHwQ"
ICOlomoc_jpg = "AgACAgIAAxkDAAIGBGCkE4EgIpHeXhH_uRo44lCxUJiyAAKXsjEb9YwgSdgCRnH8aCGDSyuFny4AAwEAAwIAA3cAA38hBAABHwQ"
ICJihlavaFake_jpg = "AgACAgIAAxkDAAIF9GCkE2sJ_AABQBDrGqGKqzMa4bHTFQACh7IxG_WMIEmDTPcKWvjL4qRoOp8uAAMBAAMCAAN3AAOVKAQAAR8E"
ICCzeshBudev_jpg = "AgACAgIAAxkDAAIF-WCkE3DXlsfNxlEqu-43bqGf3FM1AAKMsjEb9YwgSaEmzS5Cw-Z2kdmNoi4AAwEAAwIAA3cAA6Z7AgABHwQ"
ICPlzen_jpg = "AgACAgIAAxkDAAIGAWCkE3xlpFcO9FYCii7AISApTT35AAKUsjEb9YwgSehKf90yEhBV46hapC4AAwEAAwIAA3cAA_4pAQABHwQ"
ICKarVar_jpg = "AgACAgIAAxkDAAIGAmCkE30R4EZgh6MAAZnOMP9LdM1ubwAClbIxG_WMIEljT3ifxvNZSPdZpZsuAAMBAAMCAAN3AAMlBQEAAR8E"
ICLiberec_jpg = "AgACAgIAAxkDAAIF82CkE2naReLq-I91btSxrg1B1PRSAAKGsjEb9YwgSeU1U9rfmi-mLmwRpC4AAwEAAwIAA3cAA1E_AQABHwQ"
ICPardubice_jpg = "AgACAgIAAxkDAAIF9mCkE23DfDm0Tl-t_x3RjyHvLrnFAAKJsjEb9YwgSVe-zokwqbPFanYUpC4AAwEAAwIAA3cAA2hHAQABHwQ"
ICSredneCzechKrai_jpg = "AgACAgIAAxkDAAIGCGCkJ7ZXN40aYVtOGb9KGFPkCjeDAAKpsjEb9YwgSRZEXGiSAAG8vGNtAAGfLgADAQADAgADdwAD51AEAAEfBA"


# На продление карты
prodlenKart1 = 'AgACAgIAAxkDAAIKWWFErHeiLJD3EagpugPIuV55R0JFAAK5uDEbTz0pSssfPuMHNzOTAQADAgADdwADIAQ'
prodlenKart2 = ['AgACAgIAAxkDAAIKWmFErHqz7U3i7P6T4cMl2VXWrArsAAK6uDEbTz0pSk9ZrASFjPT1AQADAgADdwADIAQ']


# смотровые башни фото, по регионам

# краловеградский край
# точки на мапе
Hradec_kraloveA_tower_all_jpg = "AgACAgIAAxkDAAIqhGISmZUTIUNPwiGXxy0AAby-HqrDswAChLoxG6spmEhskuY0ZSSnfAEAAwIAA3kAAyME"
Trutnov_all_tower_jpg = "AgACAgIAAxkDAAIqh2ISmZg6HqO8n2HumXGCDEfwh67XAAKHujEbqymYSKp3YIS92fJVAQADAgADdwADIwQ"
jicin_all_tower_jpg = "AgACAgIAAxkDAAIqhmISmZe-9d5dpCAzfl7ATkTvoy_1AAKGujEbqymYSP_YFJSk0wPzAQADAgADeQADIwQ"
rychnov_nad_kneznou_all_tower_jpg = "AgACAgIAAxkDAAIqg2ISmZVhjgv7YRV8nNdDXGtDa3ZoAAKDujEbqymYSENfy7dycMqpAQADAgADdwADIwQ"
nachod_all_tower_jpg = "AgACAgIAAxkDAAIqhWISmZZDdcjEXew518Fw4iSbCRioAAKFujEbqymYSKTh2pzyM0ViAQADAgADdwADIwQ"

# фото строений
chlum_tower_jpg = "AgACAgIAAxkDAAIpBWH_4-LxYTo7Wf_DCAhT6C84PcJvAAJduTEb9bD5S1eANbH-D_rwAQADAgADeAADIwQ"
kozinec_tower_jpg = "AgACAgIAAxkDAAIpBmH_4-MgjHqXQkYCjOOnflkUrGI7AAJeuTEb9bD5S6qM9yy6a5xWAQADAgADeAADIwQ"
Osicina_tower_jpg = "AgACAgIAAxkDAAIqEmII7Fd27nO1CJMg4rGNqazqvC23AAKHtzEbNptISMCbms1pDwUiAQADAgADeAADIwQ"
varta_u_sendraze_tower_jpg = "AgACAgIAAxkDAAIpDmH_4-XnGsV6MBe_d2UVEEyhv9yvAAJmuTEb9bD5Sw2RQNEZkzJjAQADAgADeAADIwQ"
horicky_chlum_tower_jpg = "AgACAgIAAxkDAAIpDWH_4-Wm_qNr3HGk42nQ0PqQ-dv_AAJluTEb9bD5S12THmcYzK2rAQADAgADeAADIwQ"
hnedy_vrch_tower_jpg = "AgACAgIAAxkDAAIpEGH_4-ZB2BnYtOIEVYZQkmmJcL25AAJouTEb9bD5S4QPP12eAAEe8AEAAwIAA3gAAyME"
milir_tower_jpg = "AgACAgIAAxkDAAIo_WH_4-BFWVEoZGqgy-44NQbcGiLDAAJVuTEb9bD5S9QtBuFzRm0zAQADAgADeAADIwQ"
ruprechticky_spicak_tower_jpg = "AgACAgIAAxkDAAIpB2H_4-MLgEjFRA6vxpuuTpTXW344AAJfuTEb9bD5S8oR1pRyV4F9AQADAgADeAADIwQ"
na_signalu_tower_jpg = "AgACAgIAAxkDAAIpAmH_4-J2mqW0xybxiduSM-1uN3r_AAJauTEb9bD5S9CbQQwzFISFAQADAgADeAADIwQ"
vrbice_tower_jpg = "AgACAgIAAxkDAAIpD2H_4-V3MS0ySlZwK4YwMKsXcllxAAJnuTEb9bD5S8EHrus2A7QMAQADAgADeAADIwQ"
masarykova_vez_samostatnosti_tower_jpg = "AgACAgIAAxkDAAIo_mH_4-AICIyKSnDU_9hmcrV2SN0VAAJWuTEb9bD5S5iW-nT1ypuAAQADAgADeAADIwQ"
jiraskova_chata_tower_jpg = "AgACAgIAAxkDAAIo_2H_4-EmFs1kBRMQCwXK1n0hBT24AAJXuTEb9bD5Sx2n3rLzRVjTAQADAgADeAADIwQ"
Slavetinska_rozhledna_tower_jpg = "AgACAgIAAxkDAAIpCGH_4-P3vmW1UIxDcuQC6ivH5Ak4AAJguTEb9bD5S3sEnmyXu81lAQADAgADeAADIwQ"
eliska_tower_jpg = "AgACAgIAAxkDAAIpA2H_4-KHw4AZmcGAWuWM5SNS8bITAAJbuTEb9bD5SwobzN_yiUyCAQADAgADeAADIwQ"
panorama_tower_jpg = "AgACAgIAAxkDAAIpCWH_4-PUY_1yQZPscvNotqSZpqoRAAJhuTEb9bD5S7EE65ErRbQYAQADAgADeAADIwQ"
zlata_vyhlidka_tower_jpg = "AgACAgIAAxkDAAIqEWII7FfXOILPNoYBSkfGi8xm0WobAAKGtzEbNptISAwvwf_btIxbAQADAgADeAADIwQ"
predni_zaly_tower_jpg = "AgACAgIAAxkDAAIpDGH_4-RGQ4a3NFzjvWkSz5QYAn6uAAJkuTEb9bD5S2O5gsxisT73AQADAgADeAADIwQ"
anna_tower_jpg = "AgACAgIAAxkDAAIpAAFh_-PhgCGLGalL0xDVWwFBNX-uqwACWLkxG_Ww-Utyt7jN719yeAEAAwIAA3gAAyME"
pamatnik_generala_gablenze_tower_jpg = "AgACAgIAAxkDAAIo_GH_4-B21nl5Uzr0K2u26t5j4WUYAAJUuTEb9bD5Sy0AAQmMm-LjxQEAAwIAA3gAAyME"
libnikovice_tower_jpg = "AgACAgIAAxkDAAIpBGH_4-IxXlF4u7s6d5o41_Ft2WbuAAJcuTEb9bD5S0p4OJjMX01CAQADAgADeAADIwQ"
zaltman_tower_jpg = "AgACAgIAAxkDAAIpEmH_4-ff8kWEgzXSRO6d7s6HCT6XAAJquTEb9bD5S6anx_3Z4liNAQADAgADeAADIwQ"
rozhledna_na_vrchu_cap_tower_jpg = "AgACAgIAAxkDAAIpCmH_4-TmtJEZdv1WEWvcpo066iQMAAJiuTEb9bD5S6t6s_2LXpOGAQADAgADeAADIwQ"
skuhrov_nad_balou_tower_jpg = "AgACAgIAAxkDAAIpEWH_4-YjfhA5_Qb3ZOiXQjwEqMpdAAJpuTEb9bD5S2HvcJ-IdLF5AQADAgADeAADIwQ"
zvicina_tower_jpg = "AgACAgIAAxkDAAIpC2H_4-RI3pQpjcCeUunz4sz5eukyAAJjuTEb9bD5S0jO394O3-NfAQADAgADeAADIwQ"
cerovka_tower_jpg = "AgACAgIAAxkDAAIpE2H_4-ftDgTSvMsehdCDuB9hPilrAAJruTEb9bD5SxS4yDRmt2YYAQADAgADeAADIwQ"
lenka_tower_jpg = "AgACAgIAAxkDAAIqEGII7Fblg6OWCzQ8BQ9M4f90V9u5AAKFtzEbNptISCaWaEGgp_HNAQADAgADeAADIwQ"
rtyne_tower_jpg = "AgACAgIAAxkDAAIpAWH_4-HL3lDmdxzWrLRObnoFGOqNAAJZuTEb9bD5S8ahHETBERSHAQADAgADeAADIwQ"
cernohorska_raselina_tower_jpg = start_inc
zamecky_vrch_tower_jpg = start_inc



# _________________________________прага башня
# точки на мапе
prague_all_tower_jpg = "AgACAgIAAxkDAAIuxWInXBIDN5E-jqr-F3-UxYPN51QgAAJBvzEbsfA5SRVzS_Qd4gL7AQADAgADeQADIwQ"

# фото строений

zizkovsky_vysilac_pr_tower_jpg = "AgACAgIAAxkDAAItlWIZ9qIU__WnFLFtB9_2EW94lPHSAAKEuzEbYE3QSBBMFN0caaG6AQADAgADdwADIwQ"
petrinska_rozhledna_pr_tower_jpg = "AgACAgIAAxkDAAItj2IZ9pviqfI98eb6_d9VJTSjQSjNAAJ-uzEbYE3QSFSt0lMS66mBAQADAgADdwADIwQ"
astronomicka_vez_pr_tower_jpg = "AgACAgIAAxkDAAItkGIZ9ps2DTTrCPuqgjLRUl4Vfv53AAJ_uzEbYE3QSBgmooSHuHNEAQADAgADeAADIwQ"
novomlynska_vodarenska_pr_tower_jpg = "AgACAgIAAxkDAAItjWIZ9pjDX_-k1IfyLnp7avQ-OO0yAAJ8uzEbYE3QSPfEFtOlxYkkAQADAgADdwADIwQ"
doubravka_pr_tower_jpg = "AgACAgIAAxkDAAItjmIZ9ppai11voPQ8qxZYrcaUNJ7OAAJ9uzEbYE3QSBgytM1zThZMAQADAgADdwADIwQ"
obora_pr_tower_jpg = "AgACAgIAAxkDAAItkWIZ9p284sAxdUe3YyUxSo18DBVLAAKAuzEbYE3QSN4z19KR6IoLAQADAgADdwADIwQ"
barrandovske_terasy_pr_tower_jpg = "AgACAgIAAxkDAAItlGIZ9qFWTFnlLe4spESTXyihLkpyAAKDuzEbYE3QSK_g85nwdxChAQADAgADdwADIwQ"
cibulka_pr_tower_jpg = "AgACAgIAAxkDAAItjGIZ9pcuYS9zHKrTAAG1KelSAjjfzgACe7sxG2BN0EjPJIgwswUf2AEAAwIAA3cAAyME"
rozhledna_botanicka_zahrada_pr_tower_jpg = start_inc #нет фото
lahovicky_most_pr_tower_jpg = "AgACAgIAAxkDAAItl2IZ9qU1G9OWvthYw8fF-4-uPIhDAAKGuzEbYE3QSJWVGcTdytpvAQADAgADdwADIwQ"
mlikarna_v_pr_tower_jpg = "AgACAgIAAxkDAAItkmIZ9p-LVyKg1YvE24ZFQ_B-jbumAAKBuzEbYE3QSIZoWXpOm1s4AQADAgADeQADIwQ"
dum_deti_pr_tower_jpg = "AgACAgIAAxkDAAItk2IZ9qAxOnpOJMmS0RfLbDCQif0vAAKCuzEbYE3QSFJjac65V3PcAQADAgADeQADIwQ"
velka_jizni_vez_katedraly_pr_tower_jpg = "AgACAgIAAxkDAAItlmIZ9qR23Y2mhzOQ1fRUM1pSdkJnAAKFuzEbYE3QSGLfB75uUbR4AQADAgADdwADIwQ"





# _________________________________пардубицкий край башня
# точки на мапе
#
usti_nad_orlice_tower_jpg = "AgACAgIAAxkDAAI00GKA3rhs4J4Qkw6_LzEeGo8fYzcuAALAujEbyuEISAwkukibh45aAQADAgADeQADJAQ"
svitavy_tower_jpg = "AgACAgIAAxkDAAI00WKA3ri1XWSDEQlkZB9-qJVZ-o-zAALBujEbyuEISGvrr2SE4h_2AQADAgADdwADJAQ"
pardubice_tower_jpg = "AgACAgIAAxkDAAI00mKA3rk5CPCRgPebwEB54fYgCseEAALCujEbyuEISK_ZhNVvI6EKAQADAgADeQADJAQ"
chrudim_tower_jpg = "AgACAgIAAxkDAAI0z2KA3rcubfrv3BnXxHppLYQ58I_wAAK_ujEbyuEISKndiuM54dWZAQADAgADeQADJAQ"


# фото строений
Zubersky_vrch_pardubice_tower_jpg = "AgACAgIAAxkDAAIwd2Iw2EMhdtq-qjCYb7aGAAHNYynqjgAC9roxG_ngiUmIrYP2zz3y0gEAAwIAA3kAAyME"
Kozlovsky_kopec_pardubice_tower_jpg = "AgACAgIAAxkDAAIwh2Iw2E1Q31Cnjxgv1eHmxEvaUeR7AAIGuzEb-eCJSWL1cF4hGw7pAQADAgADdwADIwQ"
Stribrna_krasavice_pardubice_tower_jpg = "AgACAgIAAxkDAAIwgGIw2Egn8p1-ugRGM465RDZWsXooAAL_ujEb-eCJSejBIm2w3IsaAQADAgADeQADIwQ"
Val_pardubice_tower_jpg = "AgACAgIAAxkDAAIwdmIw2ENqOVOOHGEcLQQMTXK9y7dqAAL1ujEb-eCJSc1t_aCtJEDAAQADAgADeQADIwQ"
Suchy_vrch_pardubice_tower_jpg = "AgACAgIAAxkDAAIwg2Iw2EqsPr2yb3txZot8GQHIJujAAAICuzEb-eCJSYvev_GC7Hh_AQADAgADdwADIwQ"
Rozhledna_Klepy_pardubice_tower_jpg = "AgACAgIAAxkDAAIwhGIw2EqejR-8GwlyQZ-22bBaZdSsAAIDuzEb-eCJSWvrtE-CXXpxAQADAgADeQADIwQ"
Terezka_pardubice_tower_jpg = "AgACAgIAAxkDAAIwiWIw2E6ni8FXXpMib2VGWralvkknAAIIuzEb-eCJSaVdTvDjIp8gAQADAgADeQADIwQ"
Pastyrka_pardubice_tower_jpg = "AgACAgIAAxkDAAIweGIw2ESJm5I5g3252Njf7bYZhu5FAAL3ujEb-eCJSWVXWgtUw7M4AQADAgADdwADIwQ"
Krizova_hora_pardubice_tower_jpg = "AgACAgIAAxkDAAIwfWIw2Efs4Slt40yoXUEBeeeTVhq1AAL8ujEb-eCJSXeTaa42cXKCAQADAgADdwADIwQ"
Marianka_pardubice_tower_jpg = "AgACAgIAAxkDAAIwgWIw2ElnMndm5K3KU41FzmnTZG_6AAO7MRv54IlJtJKsTEq3ot0BAAMCAAN5AAMjBA"
Lazek_pardubice_tower_jpg = "AgACAgIAAxkDAAIwdWIw2EJ0myunrYiI5W227mrJoxKlAAL0ujEb-eCJSWs-g0Xfve9cAQADAgADdwADIwQ"
Tyrsova_rozhledna_pardubice_tower_jpg = "AgACAgIAAxkDAAIwi2Iw2E8I0PjEVt7F-03XdykZjJWXAAIKuzEb-eCJSRnjdQUFjiOOAQADAgADdwADIwQ"
Boruvka_pardubice_tower_jpg = "AgACAgIAAxkDAAIwhmIw2EzLjQY2M6353BLMatn8U3ssAAIFuzEb-eCJSWSXX8A3TgpZAQADAgADeQADIwQ"
Bara_pardubice_tower_jpg = "AgACAgIAAxkDAAIwdGIw2EJmhQS9btW0Xe5lb_KpKtbkAALzujEb-eCJSQie2r9j7vFDAQADAgADdwADIwQ"
Vojtechovska_pardubice_tower_jpg = "AgACAgIAAxkDAAIwemIw2EWQgnL39TJRtIHTidFLvrgSAAL5ujEb-eCJSY5ob2OuxCfvAQADAgADeQADIwQ"
Toulovcova_rozhledna_pardubice_tower_jpg = "AgACAgIAAxkDAAIweWIw2EUDw2iiOmxsTjsqan4PGUPnAAL4ujEb-eCJSZ_l3S-fwHeIAQADAgADdwADIwQ"
Boiika_pardubice_tower_jpg = "AgACAgIAAxkDAAIwimIw2E5kskCQ4RIx4cfL0OK8RKiFAAIJuzEb-eCJSdkf_k6pO_8UAQADAgADeQADIwQ"
Barborka_pardubice_tower_jpg = "AgACAgIAAxkDAAIwc2Iw2EJW7yPzYIXHJSgGE_tN5yMEAALyujEb-eCJSaHObby1IR9qAQADAgADeAADIwQ"
Jahudka_pardubice_tower_jpg = "AgACAgIAAxkDAAIwcmIw2EGtqFrkDC_WnyO1ge6hcRNZAALxujEb-eCJSQsKgR8_4YruAQADAgADeQADIwQ"
Milada_Lichnice_pardubice_tower_jpg = "AgACAgIAAxkDAAIwiGIw2E3Yb84aKDMT9DMyf9KRle0wAAIHuzEb-eCJSR80HIosQT_wAQADAgADeQADIwQ"
Na_Kopecku_pardubice_tower_jpg = "AgACAgIAAxkDAAIwfmIw2Ec44-cYwJ_b1uFb2FOaENcFAAL9ujEb-eCJSeQYPA91XUgpAQADAgADeAADIwQ"
Lansperk_pardubice_tower_jpg = "AgACAgIAAxkDAAIwhWIw2Eu8SV2_3zCX7kv2J9H8b-zDAAIEuzEb-eCJSZLKMFjS8XhRAQADAgADdwADIwQ"
Na_Chlumu_pardubice_tower_jpg = "AgACAgIAAxkDAAIwgmIw2EkAAW3vML5Zwnett57sgmZ60QACAbsxG_ngiUlp31ZM4r78OwEAAwIAA3cAAyME"
Kladruby_nad_Labem_pardubice_tower_jpg = "AgACAgIAAxkDAAIwfGIw2EYXWtuDw3XdiMvU80EBsSqZAAL7ujEb-eCJSbziWu0N4oMbAQADAgADdwADIwQ"
Dobre_ukryta_rozhledna_Jary_Cimrmana_tower_jpg = "AgACAgIAAxkDAAIx42JRYOtKJCaRv0-RfVlYxVgkQ3AnAAIUujEbNR-JSnUB6Yl0mjsSAQADAgADeQADIwQ"
Strazny_vrch_tower_jpg = "AgACAgIAAxkDAAIx4mJRYOrw2ay-f4ZZKaFfU3pmkkJYAAITujEbNR-JSsnj-a3m9ZJkAQADAgADdwADIwQ"

# усти над лабем tower map
# нужны фото точек на мапе
usti_nad_labem_tower_jpg = "AgACAgIAAxkDAAI02WKC0tlWUjETB2Ifbx2QFYthY30DAAKMvTEb1aURSPZ1h7TTX0OsAQADAgADeQADJAQ"
teplice_tower_jpg = "AgACAgIAAxkDAAI03GKC0ttV9vV7AseolIn7pDMHXX83AAKPvTEb1aURSEhzdQkgNVEwAQADAgADeQADJAQ"
most_tower_jpg = "AgACAgIAAxkDAAI02GKC0tmB48-TQbXV9WKBoRju-uGUAAKLvTEb1aURSKrESVJzcuHLAQADAgADeQADJAQ"
louny_tower_jpg = "AgACAgIAAxkDAAI02mKC0tnvJjJbzr0qDsxE6viY2bYzAAKNvTEb1aURSL7kBBP7cUf0AQADAgADeQADJAQ"
litomerice_tower_jpg = "AgACAgIAAxkDAAI03WKC0tvJNUwCCYs8NfjySg8nvTFNAAKQvTEb1aURSO3GeQNz-sloAQADAgADeQADJAQ"
chomutov_tower_jpg = "AgACAgIAAxkDAAI03mKC0tvxMHRFGyZwVI8eDsXluQfkAAKRvTEb1aURSKO9nQ6vZ8Z_AQADAgADeQADJAQ"
decin_tower_jpg = "AgACAgIAAxkDAAI022KC0tpb4W8s5YnhKDLn4TmLy1hLAAKOvTEb1aURSB47RCmrn5fbAQADAgADeQADJAQ"


# усти над лабем
Sokoli_vrch_tower_jpg = "AgACAgIAAxkDAAIyO2JUPExSrhTQM17AG91VXRTrzQK-AAIivjEbAAEaoEpPG1q970g9YAEAAwIAA3gAAyME"
Chmelovy_majak_v_zatci_tower_jpg = "AgACAgIAAxkDAAIyGmJUPDg0vZ3K7fgqhtwcP0U3KYjqAAIBvjEbAAEaoEp7GAt2uigZAwEAAwIAA3cAAyME"
Vlci_hora_u_Oseku_tower_jpg = "AgACAgIAAxkDAAIyJmJUPD9xIEEOk4Fl1tb8a9_tKTLMAAINvjEbAAEaoErA5EnXhsmS5AEAAwIAA3kAAyME"
Hnevin_tower_jpg = "AgACAgIAAxkDAAIyN2JUPEp4f_psoUAzk3_yAAEMtYQ31QACHr4xGwABGqBKXGTcro5fnLIBAAMCAAN3AAMjBA"
Decinsky_Sneznok_tower_jpg = "AgACAgIAAxkDAAIyKWJUPEFM5hgxGwrdjErnVYY27GuyAAIQvjEbAAEaoErvauIpiY4blQEAAwIAA3kAAyME"
Radejcin_tower_jpg = "AgACAgIAAxkDAAIyMmJUPEaqBvsbgoS8I-5nHyxW2nUVAAIZvjEbAAEaoErrY1bJJdEy_AEAAwIAA3cAAyME"
Letna_tower_jpg = "AgACAgIAAxkDAAIyNGJUPEmrMrIfO_Y_Athh_sKHLZNHAAIbvjEbAAEaoEphCAmOtmsbhQEAAwIAA3kAAyME"
Vetruse_tower_jpg = "AgACAgIAAxkDAAIyPmJUPE00f8aIsMEWmNg6_uzxpaePAAIlvjEbAAEaoErJEPv_gDKaFwEAAwIAA3kAAyME"
Hradek_tower_jpg = "AgACAgIAAxkDAAIyHmJUPDpDY7L-Mg5_wAYsdecuWCmcAAIFvjEbAAEaoErZKk2U9X_wKgEAAwIAA3kAAyME"
Jedlova_tower_jpg = "AgACAgIAAxkDAAIyM2JUPEgnWKtJ96WuTf4xNAwQOa82AAIavjEbAAEaoEpHwIw9jdbf5QEAAwIAA3kAAyME"
Schillerova_rozhledna_tower_jpg = "AgACAgIAAxkDAAIyG2JUPDjzgL54Jkg0Zmm6XnsAASmGsgACAr4xGwABGqBKHexL_EIWAAGhAQADAgADeQADIwQ"
Hasistejn_tower_jpg = "AgACAgIAAxkDAAIyHWJUPDlEI_OjGiO2T8GR59QuXV-mAAIEvjEbAAEaoErANGTUZvQtSQEAAwIAA3kAAyME"
Tanecnice_tower_jpg = "AgACAgIAAxkDAAIyI2JUPD0Tr1mPfajQIcPMLrD691w7AAIKvjEbAAEaoEouD-g9k1ImagEAAwIAA3kAAyME"
Ruzovy_vrch_tower_jpg = "AgACAgIAAxkDAAIyJGJUPD4R6D89AsmFBF01p0RSnq5BAAILvjEbAAEaoEqcuDnzeuJLdwEAAwIAA3cAAyME"
Mostka_tower_jpg = "AgACAgIAAxkDAAIyLGJUPEOqS0Dy77o_rTzbIh0Di4F8AAITvjEbAAEaoEpgqiOsolid3QEAAwIAA3kAAyME"
Krasny_Dvur_tower_jpg = "AgACAgIAAxkDAAIyOmJUPEx3JqIMYxCUYJZjj6o4TGV3AAIhvjEbAAEaoEq82Zme5QqiCQEAAwIAA3kAAyME"
Velky_Chlum_tower_jpg = "AgACAgIAAxkDAAIyJWJUPD7xTGi6BGvcYnVfPp2JO5ZyAAIMvjEbAAEaoEpKwEfP8i-o_wEAAwIAA3gAAyME"
Vlci_hora_u_Krasne_Lipy_tower_jpg = "AgACAgIAAxkDAAIyK2JUPEPSgqFCpoPLhMZNzgwvmbBAAAISvjEbAAEaoEqa8nSfL1ISYAEAAwIAA3cAAyME"
Milesovka_tower_jpg = "AgACAgIAAxkDAAIyLmJUPET7myBic36fSuFcpbCMUqRDAAIVvjEbAAEaoEpmpVRFvzeF6QEAAwIAA3kAAyME"
Pastyrska_stena_tower_jpg = "AgACAgIAAxkDAAIyPGJUPE3sWMePDk_pAgPe-SwVKV5KAAIjvjEbAAEaoEpPeh_KjI-2mQEAAwIAA3kAAyME"
Horka_tower_jpg = "AgACAgIAAxkDAAIyMGJUPEUSHo5O8Fc340bfLQ-RBvytAAIXvjEbAAEaoEq2sJYOQxNT4gEAAwIAA3cAAyME"
Studenec_tower_jpg = "AgACAgIAAxkDAAIyP2JUPFGPLIIv7iPoaGoMKt5uVZFSAAImvjEbAAEaoEoZmzEXijOUTQEAAwIAA3cAAyME"
Zamecky_vrch_tower_jpg = "AgACAgIAAxkDAAIyLWJUPESYYM52ap9RNC75JlYRRtNPAAIUvjEbAAEaoEqErff3igABK5kBAAMCAAN5AAMjBA"
Skrivanci_vrch_tower_jpg = "AgACAgIAAxkDAAIyImJUPDwAAROz59fDFq_DxlywV1HdRwACCb4xGwABGqBKC3z43d99i0kBAAMCAAN3AAMjBA"
Kratochvilova_rozhledna_tower_jpg = "AgACAgIAAxkDAAIyIGJUPDtH_asTyrvPBwsFxIHmYMQ4AAIHvjEbAAEaoEqiBkcODLMahAEAAwIAA3cAAyME"
hrad_Kostomlaty_tower_jpg = "AgACAgIAAxkDAAIyH2JUPDpCvIKt7HZ0L8mpHkPFRPYEAAIGvjEbAAEaoErijXFqR02qQwEAAwIAA3kAAyME"
Dymnik_tower_jpg = "AgACAgIAAxkDAAIyQWJUPFM_VqgE2Vf0QuSclHtZbzULAAIovjEbAAEaoEoyEBEqezh7GAEAAwIAA3kAAyME"
Svaty_kopec_tower_jpg = "AgACAgIAAxkDAAIyHGJUPDmqwd0-9CtwiZmPSxJhXzJIAAIDvjEbAAEaoEprhMFCPR9NAgEAAwIAA3kAAyME"
Varhost_tower_jpg = "AgACAgIAAxkDAAIyKGJUPECR9RvIPF3fAAHdJWeQBaRX4QACD74xGwABGqBKdWVn-LB9FEgBAAMCAAN4AAMjBA"
Vochlice_tower_jpg = "AgACAgIAAxkDAAIyNWJUPEmgVgWDVkPDVDeUmAuxDZyIAAIcvjEbAAEaoEqd4hUkvVjWYwEAAwIAA3cAAyME"
Komari_vizka_tower_jpg = "AgACAgIAAxkDAAIyQ2JUPFQrxTWtetM5T5TO4daF1vNFAAIqvjEbAAEaoEoavTierqzHWQEAAwIAA3gAAyME"
Erbenova_vyhlidka_tower_jpg = "AgACAgIAAxkDAAIyOWJUPEywZEtqPFeLbOpdbXZJlP1oAAIgvjEbAAEaoEoSPjLV4biD9wEAAwIAA3gAAyME"
Horidla_tower_jpg = "AgACAgIAAxkDAAIyMWJUPEYm1TPP82wdGcmMBbRUG3kZAAIYvjEbAAEaoEoaX4tWEcd_RgEAAwIAA3cAAyME"
Doubravska_hora_tower_jpg = "AgACAgIAAxkDAAIyL2JUPEX9i-jNT_cdHtpDlN3jzzCzAAIWvjEbAAEaoEo4gi71XqEjBQEAAwIAA3kAAyME"
Kohout_tower_jpg = "AgACAgIAAxkDAAIyQmJUPFMh7uyXp_CKFhqIf9EzaWOlAAIpvjEbAAEaoEqDmwud8cE2zQEAAwIAA3kAAyME"
Strazny_vrch_pard_tower_jpg = "AgACAgIAAxkDAAIyQGJUPFJGtobNFjMaNvFo-0_8kfaoAAInvjEbAAEaoErH-x79viSw0AEAAwIAA3kAAyME"
Cerveny_vrch_tower_jpg = "AgACAgIAAxkDAAIyGWJUPDdkOmcq4_AShM11PWeXFA-_AAO-MRsAARqgSrSSHqgq-WVlAQADAgADeQADIwQ"
Ploucnicka_vyhlidka_tower_jpg = "AgACAgIAAxkDAAIyOGJUPEvE0hoLp4svHIzOCOmv6XNAAAIfvjEbAAEaoEoiCkcIHcxocQEAAwIAA3cAAyME"
Strupcice_tower_jpg = "AgACAgIAAxkDAAIyRGJUPFRVxvoAAVIzoQ4AAaU8sL44vccAAiu-MRsAARqgSgmn0lurnCQJAQADAgADdwADIwQ"
Ruzenka_tower_jpg = "AgACAgIAAxkDAAIyJ2JUPD_9iWzSu86PVgrCI2kI784UAAIOvjEbAAEaoEqOiQX2d2tu-wEAAwIAA3cAAyME"
Stradonka_tower_jpg = "AgACAgIAAxkDAAIyPWJUPE2AEtLUCoKP7vY5LzMB8ipUAAIkvjEbAAEaoEr5LW7Eqn_gGQEAAwIAA3kAAyME"
Jerabina_tower_jpg = "AgACAgIAAxkDAAIyKmJUPEIE1EHD4Nj41AKCPm85VpuEAAIRvjEbAAEaoErKEQTgFL-0BwEAAwIAA3kAAyME"
Lovos_tower_jpg = "AgACAgIAAxkDAAIyIWJUPDtoqGRggjNnCnuEz11LAAFMSwACCL4xGwABGqBK5lrwPJwAAYw9AQADAgADdwADIwQ"
Hazmburk_tower_jpg = "AgACAgIAAxkDAAIyNmJUPEqDIGgnVJxop9C4TbGE-tI1AAIdvjEbAAEaoEqlml_kYBD1SQEAAwIAA3kAAyME"

Sibenik_tower_jpg = photo_kotorogo_net #нужны фото с этой башни
Straziste_u_Chomutova_tower_jpg = photo_kotorogo_net #нужны фото с этой башни
Male_Sedlo_tower_jpg = photo_kotorogo_net #нужны фото с этой башни
Rohatce_tower_jpg = photo_kotorogo_net #нужны фото с этой башни
Lucemburkuv_kopec_tower_jpg = photo_kotorogo_net #нужны фото с этой башни


# места для фото praha прага
# точки на мапе
photoMap_prague = "AgACAgIAAxkDAAI0zGJ39aL_Shg_vDePiSC0D8aUksTmAALZujEbGM_BS3TSZn8IXwjfAQADAgADeAADJAQ"

photoMap_novy_svet = "AgACAgIAAxkDAAIzU2Jj98fpdUVwpm7XKx50fa-IMjpJAAKPuTEbBnMhSzWZIthFBlehAQADAgADeAADJAQ"
photoMap_vitkov = "AgACAgIAAxkDAAIzT2Jj98VWzEQS8TrexE8Ho7QLhggKAAKLuTEbBnMhSxyD1RGK1cicAQADAgADeAADJAQ"
photoMap_lucerna = "AgACAgIAAxkDAAIzUGJj98V54GWznMX4grplqRGPbxpeAAKMuTEbBnMhS4lKIf9Lnkc-AQADAgADeAADJAQ"
photoMap_dox = "AgACAgIAAxkDAAIzUWJj98UX7rb-CKg319P4KltQb9zWAAKNuTEbBnMhS_RfrXYq7KH5AQADAgADeAADJAQ"
photoMap_grand_cafe = "AgACAgIAAxkDAAIzVWJj98ikb3CYSpvYiW9syQlmT-tTAAKRuTEbBnMhS6cyZW0_FPi7AQADAgADeAADJAQ"
photoMap_letka_cafe = "AgACAgIAAxkDAAIzWmJj98oT26JYe7LWRAOV5MrTVOGGAAKWuTEbBnMhSx1EQzRKTNZ5AQADAgADeAADJAQ"
photoMap_grebovka = "AgACAgIAAxkDAAIzUmJj98eBNoqz_TYMt0uFDwFcfZtYAAKOuTEbBnMhS19fdh44z5ZeAQADAgADdwADJAQ"
photoMap_dripstone_wall = "AgACAgIAAxkDAAIzVGJj98ck7o2nlp58vdD2q0987-eYAAKQuTEbBnMhS63LH3S06lNbAQADAgADeQADJAQ"
photoMap_radotinsky_most = "AgACAgIAAxkDAAIzV2Jj98hQvMMDkg7CcmFTczucey4eAAKTuTEbBnMhS131XsNv-9IaAQADAgADeAADJAQ"
photoMap_trojsky_most = "AgACAgIAAxkDAAIzWWJj98lpiziclxyoohb_jYm8tJinAAKVuTEbBnMhS3HZyYo-oJiQAQADAgADdwADJAQ"
photoMap_letna = "AgACAgIAAxkDAAIzWGJj98kECtIRr2uL2kkgGm-hs_w7AAKUuTEbBnMhS4QpdaCEIFYHAQADAgADeAADJAQ"
photoMap_vrtbovska_zahrada = "AgACAgIAAxkDAAIzVmJj98j31DVak4wvIQkaiay8Jvg9AAKSuTEbBnMhS6Y-9VljgmDNAQADAgADeQADJAQ"
